spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/category-service/
            - classpath:config/comment-service/
            - classpath:config/compilation-service/
            - classpath:config/event-service/
            - classpath:config/request-service/
            - classpath:config/user-service/
            - classpath:config/stats-server/
            - classpath:config/gateway-server/
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/