spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        max-attempts: 30
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

server:
  port: 0