services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: stat_user
      POSTGRES_PASSWORD: stat_password
      POSTGRES_DB: ewm_stats_db
    volumes:
      - ./stats/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  category-db:
    image: postgres:16.1
    container_name: category-service-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: category_service
      POSTGRES_PASSWORD: category_password
      POSTGRES_DB: category_db
    volumes:
      - ./core/category-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - category-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  comment-db:
    image: postgres:16.1
    container_name: comment-service-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: comment_service
      POSTGRES_PASSWORD: comment_password
      POSTGRES_DB: comment_db
    volumes:
      - ./core/comment-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - comment-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  compilation-db:
    image: postgres:16.1
    container_name: compilation-service-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: compilation_service
      POSTGRES_PASSWORD: compilation_password
      POSTGRES_DB: compilation_db
    volumes:
      - ./core/compilation-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - compilation-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  event-db:
    image: postgres:16.1
    container_name: event-service-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: event_service
      POSTGRES_PASSWORD: event_password
      POSTGRES_DB: event_db
    volumes:
      - ./core/event-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - event-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  request-db:
    image: postgres:16.1
    container_name: request-service-db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: request_service
      POSTGRES_PASSWORD: request_password
      POSTGRES_DB: request_db
    volumes:
      - ./core/request-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - request-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-db:
    image: postgres:16.1
    container_name: user-service-db
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    volumes:
      - ./core/user-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic stats.user-actions.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic stats.events-similarity.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true

volumes:
  stats-db-data:
  category-db-data:
  comment-db-data:
  compilation-db-data:
  event-db-data:
  request-db-data:
  user-db-data: