package ru.practicum.ewm.stats.client;

import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;
import ru.practicum.ewm.stats.client.props.ClientProperties;
import ru.practicum.ewm.stats.dto.EndpointHitDto;
import ru.practicum.ewm.stats.dto.ViewStatsDto;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Клиент для взаимодействия с сервисом статистики просмотров.
 * 
 * StatsClient отвечает за отправку информации о посещениях (hits) и получение
 * статистики просмотров из внешнего сервиса статистики через REST API.
 * 
 * Основная функциональность:
 * - Отправка информации о посещениях endpoint'ов (метод hit)
 * - Получение статистики просмотров для конкретных URI (метод stats)
 * - Получение количества просмотров для события (метод viewsForEvent)
 * - Поддержка повторных попыток отправки при сбоях с экспоненциальной задержкой
 * 
 * Конфигурация:
 * Клиент инициализируется с параметрами конфигурации через ClientProperties:
 * - baseUrl - базовый URL сервиса статистики
 * - connectTimeout - таймаут подключения
 * - readTimeout - таймаут чтения
 * - hitMaxAttempts - максимальное количество попыток отправки hit
 * - hitBackoffMillis - начальная задержка между повторными попытками
 * - hitBackoffCapMillis - максимальная задержка между попытками
 * 
 * Механизм повторных попыток:
 * При отправке hit используется экспоненциальная стратегия повторов:
 * - При неудаче клиент повторяет запрос до hitMaxAttempts раз
 * - Задержка между попытками увеличивается экспоненциально: delay = baseBackoff * 2^(attempt-1)
 * - Задержка ограничена значением hitBackoffCapMillis
 * - Если все попытки исчерпаны, операция завершается без исключения (graceful degradation)
 * 
 * Примеры использования:
 * // Отправка hit для URI
 * statsClient.hit("/events/1", "192.168.1.1");
 * 
 * // Получение количества просмотров события
 * long views = statsClient.viewsForEvent(1L);
 * 
 * // Получение детальной статистики
 * List&lt;ViewStatsDto&gt; stats = statsClient.stats(
 *     LocalDateTime.of(2025, 1, 1, 0, 0),
 *     LocalDateTime.now(),
 *     List.of("/events/1", "/events/2"),
 *     true // только уникальные IP
 * );
 *
 * Формат даты/времени:
 * Все даты передаются в формате "yyyy-MM-dd HH:mm:ss", при отправке на сервер
 * пробел заменяется на '+' для корректной передачи в query-параметрах URL.
 * 
 * @see EndpointHitDto
 * @see ViewStatsDto
 * @see ClientProperties
 */
@Slf4j
public class StatsClient {

    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final RestTemplate rest;
    private final ClientProperties props;
    private final String appName;

    /**
     * Создаёт новый экземпляр StatsClient с заданными параметрами.
     * 
     * @param builder RestTemplateBuilder для создания REST-клиента
     * @param props настройки клиента ClientProperties
     * @param appName имя приложения (берётся из spring.application.name), используется
     *                для идентификации источника hit'ов в сервисе статистики
     */
    public StatsClient(@NonNull RestTemplateBuilder builder,
                       @NonNull ClientProperties props,
                       @Value("${spring.application.name:ewm-service}") String appName) {
        this.props = props;
        this.appName = appName;
        this.rest = builder
                .rootUri(props.getBaseUrl())
                .setConnectTimeout(props.getConnectTimeout())
                .setReadTimeout(props.getReadTimeout())
                .build();
        log.debug("StatsClient initialized: baseUrl={}, connectTimeout={}, readTimeout={}, hitMaxAttempts={}, hitBackoff={}ms, app={}",
                props.getBaseUrl(), props.getConnectTimeout(), props.getReadTimeout(),
                props.getHitMaxAttempts(), props.getHitBackoffMillis(), appName);
    }

    /**
     * Отправляет информацию о посещении (hit) указанного URI с IP-адреса клиента.
     * 
     * Метод создаёт EndpointHitDto с текущей меткой времени и
     * делегирует отправку перегруженному методу hit(EndpointHitDto).
     * 
     * При ошибках отправки выполняются повторные попытки согласно настройкам
     * hitMaxAttempts и hitBackoffMillis. Если все попытки исчерпаны, метод
     * завершается без исключения (статистика может быть потеряна).
     * 
     * @param uri URI запроса, который был посещён (не может быть null или пустым)
     * @param ip IP-адрес клиента (не может быть null или пустым)
     * @throws NullPointerException если uri или ip равны null
     */
    public void hit(@NonNull String uri, @NonNull String ip) {
        EndpointHitDto dto = new EndpointHitDto(
                0L, // id will be generated by the server
                appName,
                uri.trim(),
                ip,
                LocalDateTime.now()
        );
        hit(dto);
    }

    /**
     * Отправляет информацию о посещении (hit) в сервис статистики.
     * 
     * Выполняет POST-запрос на endpoint /hit сервиса статистики.
     * При неудаче выполняет повторные попытки с экспоненциальной задержкой.
     * 
     * Стратегия повторов:
     * - Попытка 1: немедленно
     * - Попытка 2: задержка = hitBackoffMillis
     * - Попытка 3: задержка = hitBackoffMillis * 2
     * - Попытка N: задержка = hitBackoffMillis * 2^(N-1), но не более hitBackoffCapMillis
     * 
     * При исчерпании всех попыток или при неожиданной ошибке метод завершается
     * без исключения, логируя предупреждение. Это обеспечивает graceful degradation -
     * основная функциональность приложения продолжает работать даже при недоступности
     * сервиса статистики.
     * 
     * @param dto DTO с информацией о посещении (не может быть null)
     * @throws NullPointerException если dto равен null
     */
    public void hit(@NonNull EndpointHitDto dto) {
        int attempt = 1;
        final int max = props.getHitMaxAttempts();
        final long baseBackoff = props.getHitBackoffMillis();
        final long cap = props.getHitBackoffCapMillis();

        while (true) {
            try {
                // сервер возвращает 201 + json с записанным хит-DTO
                rest.postForEntity("/hit", dto, EndpointHitDto.class);
                log.info("Hit sent successfully: id={}, uri={}", dto.getId(), dto.getUri());
                if (log.isTraceEnabled()) {
                    log.trace("POST /hit sent: app={}, uri={}, ip={}, ts={}",
                            dto.getApp(), dto.getUri(), dto.getIp(), dto.getTimestamp());
                }
                return;
            } catch (RestClientException ex) {
                if (attempt >= max) {
                    log.warn("StatsClient: POST /hit failed after {} attempt(s). Continue without stats. reason={}",
                            attempt, ex.toString(), ex);
                    return;
                }
                long delay = baseBackoff * (1L << (attempt - 1));
                if (delay > cap) delay = cap;
                log.info("StatsClient: POST /hit failed on attempt {}/{}. Retry in {} ms. reason={}",
                        attempt, max, delay, ex.toString());
                safeSleep(delay);
                attempt++;
            } catch (RuntimeException ex) {
                log.info("StatsClient: unexpected error on POST /hit. Continue without stats. {}", ex.toString(), ex);
                return;
            }
        }
    }

    /**
     * Получает количество просмотров для конкретного события.
     * 
     * Формирует URI в формате "/events/{eventId}" и запрашивает статистику
     * уникальных просмотров за весь период (с 2000-01-01 до текущего момента).
     * 
     * @param eventId идентификатор события (не может быть null)
     * @return количество уникальных просмотров события, или 0 в случае ошибки
     * @throws NullPointerException если eventId равен null
     */
    public long viewsForEvent(@NonNull Long eventId) {
        return viewsForUri("/events/" + eventId, true);
    }

    /**
     * Получает количество просмотров для указанного URI.
     * 
     * Запрашивает статистику за весь доступный период (с 2000-01-01 до текущего момента).
     * Если статистика недоступна или произошла ошибка, возвращает 0.
     * 
     * @param uri URI, для которого нужно получить статистику (не может быть null)
     * @param unique если true - считаются только уникальные IP, если false - все просмотры
     * @return количество просмотров, или 0 в случае ошибки
     * @throws NullPointerException если uri равен null
     */
    public long viewsForUri(@NonNull String uri, boolean unique) {
        try {
            List<ViewStatsDto> list = stats(
                    LocalDateTime.of(2000, 1, 1, 0, 0, 0),
                    LocalDateTime.now(),
                    List.of(uri.trim()),
                    unique
            );
            return list.stream()
                    .filter(v -> uri.trim().equals(v.getUri()))
                    .mapToLong(ViewStatsDto::getHits)
                    .sum();
        } catch (Exception e) {
            log.warn("Stats unavailable for {}: {}", uri, e.toString());
            return 0L;
        }
    }

    /**
     * Получает детальную статистику просмотров за указанный период.
     * 
     * Выполняет GET-запрос к endpoint /stats сервиса статистики с параметрами:
     * - start - начало периода (формат: yyyy-MM-dd HH:mm:ss)
     * - end - конец периода (формат: yyyy-MM-dd HH:mm:ss)
     * - uris - список URI для фильтрации (опционально)
     * - unique - флаг подсчёта только уникальных IP
     * 
     * Результат содержит список ViewStatsDto с информацией о количестве
     * просмотров для каждого URI, отсортированный по убыванию количества просмотров.
     * 
     * @param start начало временного диапазона (не может быть null, должен быть раньше end)
     * @param end конец временного диапазона (не может быть null, должен быть позже start)
     * @param uris список URI для фильтрации статистики (может быть null или пустым для получения
     *             статистики по всем URI)
     * @param unique если true - учитываются только уникальные IP-адреса,
     *               если false - все просмотры
     * @return список ViewStatsDto со статистикой просмотров, отсортированный по убыванию hits,
     *         или пустой список если данных нет
     * @throws NullPointerException если start или end равны null
     */
    public List<ViewStatsDto> stats(@NonNull LocalDateTime start,
                                    @NonNull LocalDateTime end,
                                    List<String> uris,
                                    boolean unique) {
        StringBuilder qs = new StringBuilder()
                .append("/stats")
                .append("?start=").append(fmt(start))
                .append("&end=").append(fmt(end))
                .append("&unique=").append(unique);

        if (uris != null && !uris.isEmpty()) {
            for (String u : uris) {
                qs.append("&uris=").append(u.trim());
            }
        }

        ResponseEntity<ViewStatsDto[]> resp = rest.getForEntity(qs.toString(), ViewStatsDto[].class);
        ViewStatsDto[] body = resp.getBody();
        return (body == null) ? Collections.emptyList() : Arrays.asList(body);
    }

    /**
     * Безопасно приостанавливает выполнение потока на указанное количество миллисекунд.
     * 
     * Используется для реализации задержки между повторными попытками отправки hit.
     * Если поток прерывается во время ожидания, восстанавливает флаг прерывания
     * и логирует предупреждение.
     * 
     * @param millis количество миллисекунд для ожидания
     */
    private void safeSleep(long millis) {
        try {
            if (millis > 0) Thread.sleep(millis);
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            log.warn("StatsClient: retry sleep interrupted; giving up retries.");
        }
    }

    /**
     * Форматирует LocalDateTime в строку для использования в URL query-параметрах.
     * 
     * Преобразует дату в формат "yyyy-MM-dd HH:mm:ss", затем заменяет пробел на '+'.
     * Это необходимо для корректной передачи даты в URL без дополнительного кодирования.
     * 
     * @param dt дата и время для форматирования
     * @return отформатированная строка в формате "yyyy-MM-dd+HH:mm:ss"
     */
    private static String fmt(LocalDateTime dt) {
        return FMT.format(dt).replace(' ', '+');
    }
}
