DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(9) NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_requests_event_requester ON requests(event_id, requester_id);
CREATE INDEX IF NOT EXISTS ix_requests_event_id ON requests(event_id);
CREATE INDEX IF NOT EXISTS ix_requests_requester_id ON requests(requester_id);
CREATE INDEX IF NOT EXISTS ix_requests_status ON requests(status);
