-- ЧИСТКА
DROP TABLE IF EXISTS compilation_events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS comments CASCADE;  -- Добавлено
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ПОЛЬЗОВАТЕЛИ
CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

-- КАТЕГОРИИ
CREATE TABLE IF NOT EXISTS categories (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- СОБЫТИЯ
CREATE TABLE IF NOT EXISTS events (
    id BIGSERIAL PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    title VARCHAR(120) NOT NULL,
    category_id  BIGINT NOT NULL REFERENCES categories(id),
    initiator_id BIGINT NOT NULL REFERENCES users(id),
    event_date   TIMESTAMP NOT NULL,
    created_on   TIMESTAMP NOT NULL DEFAULT now(),
    published_on TIMESTAMP NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit   INT NOT NULL DEFAULT 0,
    request_moderation  BOOLEAN NOT NULL DEFAULT TRUE,
    state VARCHAR(16) NOT NULL CHECK (state IN ('PENDING','PUBLISHED','CANCELED')),
    location_lat DOUBLE PRECISION NOT NULL,
    location_lon DOUBLE PRECISION NOT NULL
);

-- КОММЕНТАРИИ (улучшенная версия)
CREATE TABLE IF NOT EXISTS comments (
    id BIGSERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,  -- Улучшено: SET NULL при удалении пользователя
    published_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,  -- Удалять комментарии при удалении события
    deleted BOOLEAN DEFAULT FALSE NOT NULL,

    -- Проверка на пустой текст
    CONSTRAINT comments_text_not_empty CHECK (LENGTH(TRIM(text)) > 0)
);

-- ЗАЯВКИ НА УЧАСТИЕ
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT REFERENCES events(id),
    requester_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(9) NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

-- ПОДБОРКИ (compilations)
CREATE TABLE IF NOT EXISTS compilations (
    id      BIGSERIAL PRIMARY KEY,
    pinned  BOOLEAN NOT NULL DEFAULT FALSE,
    title   VARCHAR(50) NOT NULL UNIQUE
);

-- Связь "подборка -> события"
CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id)       REFERENCES events(id)       ON DELETE CASCADE
);

-- ИНДЕКСЫ
CREATE INDEX IF NOT EXISTS ix_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS ix_events_state      ON events(state);
CREATE INDEX IF NOT EXISTS ix_events_category   ON events(category_id);
CREATE INDEX IF NOT EXISTS ix_events_paid       ON events(paid);
CREATE INDEX IF NOT EXISTS ix_events_initiator  ON events(initiator_id);  -- Добавлено

CREATE INDEX IF NOT EXISTS ix_compilations_pinned ON compilations(pinned);
CREATE INDEX IF NOT EXISTS ix_compilation_events_event ON compilation_events(event_id);

-- Индексы для таблицы comments (добавлены)
CREATE INDEX IF NOT EXISTS ix_comments_event_id ON comments(event_id);
CREATE INDEX IF NOT EXISTS ix_comments_user_id ON comments(user_id);
CREATE INDEX IF NOT EXISTS ix_comments_deleted ON comments(deleted);
CREATE INDEX IF NOT EXISTS ix_comments_published_on ON comments(published_on);
CREATE INDEX IF NOT EXISTS ix_comments_event_deleted ON comments(event_id, deleted);  -- Составной индекс

-- Индексы для requests (добавлены)
CREATE INDEX IF NOT EXISTS ix_requests_event_id ON requests(event_id);
CREATE INDEX IF NOT EXISTS ix_requests_requester_id ON requests(requester_id);
CREATE INDEX IF NOT EXISTS ix_requests_status ON requests(status);
CREATE INDEX IF NOT EXISTS ix_requests_event_requester ON requests(event_id, requester_id);  -- Для проверки дубликатов