server:
  port: 0

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5436/comment_db
    username: comment_service
    password: comment_password

resilience4j:
  circuitbreaker:
    instances:
      UserServiceClientgetUserById:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      RequestServiceClientgetByRequesterById:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      EventServiceClientgetEventById:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    instances:
      UserServiceClientgetUserById:
        timeoutDuration: 2s
      RequestServiceClientgetByRequesterById:
        timeoutDuration: 2s
      EventServiceClientgetEventById:
        timeoutDuration: 2s

logging:
  level:
    root: INFO
    ru.practicum: DEBUG