server:
  port: 0

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/event_db
    username: event_service
    password: event_password

resilience4j:
  circuitbreaker:
    instances:
      CategoryServiceClientgetCategoriesByIds:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      CategoryServiceClientgetCategoryById:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      RequestServiceClientgetCountByEventIdsAndStatus:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      RequestServiceClientgetCountByEventIdAndStatus:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      RequestServiceClienthasUserIdAttendEventId:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      UserServiceClientgetUsersByIds:
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
      UserServiceClientgetUserById:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    instances:
      CategoryServiceClientgetCategoriesByIds:
        timeoutDuration: 2s
      CategoryServiceClientgetCategoryById:
        timeoutDuration: 2s
      RequestServiceClientgetCountByEventIdsAndStatus:
        timeoutDuration: 2s
      RequestServiceClientgetCountByEventIdAndStatus:
        timeoutDuration: 2s
      RequestServiceClienthasUserIdAttendEventId:
        timeoutDuration: 2s
      UserServiceClientgetUsersByIds:
        timeoutDuration: 2s
      UserServiceClientgetUserById:
        timeoutDuration: 2s

grpc:
  server:
    port: -1
  client:
    collector:
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    analyzer:
      address: discovery:///analyzer
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    root: INFO
    ru.practicum: DEBUG